### PR TITLE
Add support for Flask-Login to plotly/dash-auth

### PR DESCRIPTION
**Pull request by gaw89**
There was a [PR](https://github.com/plotly/dash/pull/138) a while back to add support for the Flask-Login extension.  It appeared there were some issues merging this with the main Dash package and nothing has happened since then on this end.  I thought it would be more appropriate to add the support here in dash-auth.  I used the idea of that PR and added a new class `DashFlaskLogin` to be used in place of the standard `Dash` class.  It adds an authentication_required parameter to the `__init__`.

I look forward to your feedback!

### CODE REVIEW

**Comment by chriddyp** [comment]
Thanks @gaw89 ! Yes, I think that I like it in this package as well.

Could you create a simple example that shows how this would be used? Thanks!

**Comment by gaw89** [comment]
I'm back in the office now, and I'll work on an example the next couple days.  Once I have the example up and running, I'll submit it in a PR to dash-docs.

Thanks!

**Comment by gaw89** [comment]
@chriddyp, I got this working using three separate Dash apps - one for login, one for logout, and the actual Dash app.  Here it is in action:

flask_login_demo

The code is in [this gist](https://gist.github.com/gaw89/57e3bc887131f26d20ede348ca0d31f9).  I used an html.Form on the login screen, which allows the user to log in by pressing Enter (rather than just using html.Button which currently requires the user to actually click with the mouse).  Sometimes, I find that I have to enter login credentials twice.  I think this has something to do with how the callback is fired.

As I've been working through this however, I feel that the complexity of the API in its current state is a little high.  It requires the user to create three separate apps and to directly use certain elements of Flask-Login such as the `LoginManager`, `login_user`, `logout_user`, as well as needing to create a User class (which is actually pretty simple with `flask_login.UserMixin`).  I think all this complexity somewhat detracts from the (fantastic) plug and play nature of Dash.  The usage example currently sits at 166 LOC, which is quite a bit higher than other examples in Dash-Auth.

Because of this, I have also begun working on a version that includes default views for login and logout.  The example for this version is a mere 52 LOC, and you can find the code [here](https://gist.github.com/gaw89/956d0d857feaf04206dd18fc776dde3f).  This uses standard Flask templates and views for login and logout.  It encapsulates all of the user authorization and management functionality and is basically plug and play.  It can be as simple as just providing a list of `('USERNAME', 'PASSWORD')` tuples but will also support database connections (I'm implementing Sqlite3 today, and will work on SQLAlchemy later).  Here's an example of this version in action:

flask_login_with_default_views_demo

I am wondering if the version with the default views should be a separate Dash extension entirely...  I look forward to your thoughts!

**Comment by gaw89** [comment]
I'll plan to hold off on a PR for dash-docs until we decide the best course of action re. an entirely new extension.

**Comment by chriddyp** [comment]
Thanks @gaw89 ! I plan on digging into this later today or early this week.

**Comment by gaw89** [comment]
Great, thanks for your consideration Chris!

**Comment by chriddyp** [comment]
Alright, I'm taking a look at this now

**Comment by gaw89** [comment]
Thanks for such detailed feedback on the PR!

I'm trying this out right now, and it works great.  This definitely solves basically everything I was working to solve.  One question I have, how would you allow the user to change their password in this case?  Would it be through a callback?  I cannot think of another way to do this with #18, but maybe there's something I'm missing?

The one thing that this may not solve (which using Flask-Login does if you also use Flask directly for the login/out views), is message flashing.  I feel that this might be confusing to end-users:

dash-oauth-login

When this happens, I'm not really sure what I did wrong.  I think from a UX standpoint, it's useful to simply have something like "LOGIN FAILED!" appear in red text when I get redirected back to the login screen.  This is easy to do with Flask's flash method, but I can't think of a way to do it through Dash.  I've tried with callbacks, but, depending on the order in which the callbacks fire, the text usually just appears for a split second then goes away.

I'll definitely consider maintaining this in a ```dash-flask-login``` package.  Do you think there'd be interest in this from the Dash community?

Thanks again for your detailed response!

**Comment by chriddyp** [comment]
> When this happens, I'm not really sure what I did wrong. I think from a UX standpoint, it's useful to simply have something like "LOGIN FAILED!" appear in red text when I get redirected back to the login screen. This is easy to do with Flask's flash method, but I can't think of a way to do it through Dash. I've tried with callbacks, but, depending on the order in which the callbacks fire, the text usually just appears for a split second then goes away.

Unfortunately, I don't think that this is possible right now - the `POST` of the form updates the URL before Dash can respond with the UI.

However, I think that there will be a few ways that we can address this:
1. Once `href` is supported in `dcc.Location` as per the recent discussion in https://github.com/plotly/dash-core-components/issues/81, the `POST` could maybe update the url to be `/auth/login#failed` or `auth/login?status=failed` and then the login screen could display a message depending on the URL
2. We're only performing a `POST` in that PR so that we can set cookies, see https://github.com/plotly/dash-auth/blob/26c2fcce2118a35d5f06ab366ebc00adfbef92d3/dash_auth/dash_oauth.py#L129-L150. If we had a `dcc.Cookie` element, we might be able to manage these cookies entirely through dash component callbacks

**Comment by ljaraque** [comment]
Hi @gaw89 and @chriddyp 
I am looking forward to using these login methods to embed dash into my own flask app with single authentication point. Are the items discussed above going to be merged in some way into dash master branch? or will there be any `flash-flask-login` like package as suggested by @gaw89 ? Sorry in advance if I missed something from the discussion above, if this is already clear.

**Comment by gaw89** [comment]
@ljaraque, I am planning to release a ```dash-flask-login``` package at some point in the relatively near future.  In the meantime, if you want to use the functionality introduced above, you should be able to pip install:

```pip install https://github.com/gaw89/dash-auth/archive/v0.1.0.zip```

**Comment by AfroMetal** [comment]
@gaw89 Could you inform here when the `dash-flask-login` package will be available? I am using now `Flask-Login` for Dash in some hacky and not the safest way and would really appreciate package like that.

**Comment by gaw89** [comment]
@AfroMetal, hopefully in the relatively near future.  It just depends on when I have time to get to it.  In the meantime, you can pip install my unofficial version of dash-auth with this:

```pip install https://github.com/gaw89/dash-auth/archive/v0.1.0.zip```

And that will allow you to use Flask-Login.

**Comment by gaw89** [comment]
@ljaraque @AfroMetal, Dash-Flask-Login is now available [here](https://github.com/gaw89/dash-flask-login) or via pip: ```pip install dash-flask-login```.  

This is the initial release and lacks a bit of functionality and docs are somewhat incomplete, but you can get the idea from the usage examples on the Github page.  I will work on improvements/feature additions in the coming months!

**Pull request closed without merging**
