### PR TITLE
Adding user defined authentication function as parameter

### PR DESCRIPTION
**Pull request by michaels0m**
This pull request would allow users to pass their own python function to dash_auth.BasicAuth() so that the usernames and passwords do not have to be stored as plain strings and can simply be stored as the result of a user defined function (e.g. the hash of the password can be stored instead of the password itself).

### CODE REVIEW

**Comment by michaels0m** [comment]
@alexcjohnson - I would appreciate any feedback you have on this PR. I was not sure on the best way to incorporate the change into the unit tests so I have not added them in yet. Also, I have used a try-except clause when running the auth_func to ensure that if there is an error, it acts the same as invalid credentials, but should the error be printed out for the developer to see?

**Comment by michaels0m** [comment]
Thank you @alexcjohnson! That is a great suggestion, I have gone ahead and incorporated it in so that either the username/password map or the user-defined authorization function can be used.

I have also added in a print statement which will print any Exceptions raised by the authorization function. The reason I was cautious to do so at the beginning was because if the authorization function is misspecified then it may print the username and/or password which could be a security risk, but I guess this responsibility should fall on the developer creating the authorization function.

**Comment by alexcjohnson** [comment]
Nicely done, looks great! Would you mind adding a test of the function form to https://github.com/plotly/dash-auth/blob/master/tests/test_basic_auth_integration.py? We can either parametrize the existing test or copy it to a new one (would be called `test_ba002_...`) and modify that to use a function. Bonus points if you also add a test of the errors raised on improper init 😉 

After that we just need a changelog entry and we'll be ready to go.

**Comment by michaels0m** [comment]
I created a new file for the new unit tests, updated the CHANGELOG and README and added pytest to the dev requirements. I went for the bonus points and added in a test for the errors raised on improper init 😁 . Let me know what you think!

**Review by alexcjohnson — APPROVED** [review]
💃 Excellent, thanks! (And apologies for the delay reviewing, holidays etc etc, I'll try to get this released in the next couple of days)

**Comment by alexcjohnson** [comment]
v2.1.0 is published, please test it out and LMK if you encounter any issues with it!

**Comment by michaels0m** [comment]
@alexcjohnson - Thank you for publishing v2.1.0! I tested it out on my side and it seems to be working well but I will keep an eye out for any issues raised by other users. Thanks again!

**Pull request merged**
